import React, { useEffect, useState } from 'react';
import { LockKeyhole, Send, X } from 'lucide-react';
import { auth, collection, db, doc, getDoc, onSnapshot, query, where } from '../lib/firebase';
import { decryptScheduledMessage, encryptScheduledMessage } from '../utils/scheduledMessages';

export function ScheduledMessagesModal({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const [content, setContent] = useState(''); const [unlockAt, setUnlockAt] = useState(''); const [messages, setMessages] = useState<any[]>([]); const [opened, setOpened] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const [sending, setSending] = useState(false);
  useEffect(() => { if (!isOpen || !auth.currentUser) return; const ref = collection(db, 'couples', 'our_couple', 'scheduled_messages'); return onSnapshot(query(ref, where('recipientUid', '==', auth.currentUser.uid)), (snap) => setMessages(snap.docs.map((item) => ({ id: item.id, ...item.data() })))); }, [isOpen]);
  const send = async () => { try { setSending(true); setError(''); const user = auth.currentUser; if (!user) throw new Error('Hãy đăng nhập trước.'); const couple = (await getDoc(doc(db, 'couples', 'our_couple'))).data() as any; const recipientUid = couple?.user1Uid === user.uid ? couple?.user2Uid : couple?.user1Uid; if (!recipientUid) throw new Error('Chưa tìm thấy tài khoản đối phương.'); const encrypted = await encryptScheduledMessage(content, new Date(unlockAt).toISOString()); const token = await user.getIdToken(); const response = await fetch('/api/scheduled-messages/create', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ coupleId: 'our_couple', recipientUid, ...encrypted }) }); if (!response.ok) throw new Error((await response.json()).error || 'Không gửi được thư.'); setContent(''); setUnlockAt(''); } catch (cause: any) { setError(cause?.message || 'Không gửi được thư.'); } finally { setSending(false); } };
  const openMessage = async (message: any) => { try { const token = await auth.currentUser?.getIdToken(); const response = await fetch('/api/scheduled-messages/key', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ coupleId: 'our_couple', messageId: message.id }) }); if (!response.ok) throw new Error('Thư chưa thể mở.'); const { key } = await response.json(); const plaintext = await decryptScheduledMessage({ ...message, key }); setOpened((current) => ({ ...current, [message.id]: plaintext })); } catch (cause: any) { setError(cause?.message || 'Không thể mở thư.'); } };
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-[60] flex items-end justify-center bg-slate-900/45 p-3"><div className="w-full max-w-lg rounded-3xl bg-white p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-slate-800">Đôi lời muốn nói</h2><p className="text-xs text-slate-500">Gửi một lời nhắn chỉ mở đúng lúc.</p></div><button onClick={onClose} className="rounded-full bg-slate-100 p-2"><X className="h-4 w-4" /></button></div><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Viết điều muốn nói..." className="w-full rounded-2xl border border-slate-200 p-3 text-sm" rows={4} /><input value={unlockAt} onChange={(event) => setUnlockAt(event.target.value)} type="datetime-local" className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm" /><button disabled={sending} onClick={send} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-rose-500 p-3 text-sm font-bold text-white disabled:opacity-50"><Send className="h-4 w-4" />{sending ? 'Đang khóa thư...' : 'Gửi lời nhắn'}</button>{error && <p className="mt-2 text-xs text-rose-600">{error}</p>}<div className="mt-5 space-y-2"><p className="text-xs font-bold text-slate-500">HỘP THƯ ĐẾN</p>{messages.map((message) => { const isUnlocked = Date.parse(message.unlockAt) <= Date.now(); return <button onClick={() => isUnlocked && !opened[message.id] && openMessage(message)} key={message.id} className="w-full rounded-2xl border border-slate-100 p-3 text-left text-sm">{opened[message.id] ? <span className="text-slate-700">{opened[message.id]}</span> : isUnlocked ? <span className="text-rose-600">Thư đã mở — chạm để đọc</span> : <span className="flex items-center gap-2 text-slate-500"><LockKeyhole className="h-4 w-4" />Thư sẽ mở lúc {new Date(message.unlockAt).toLocaleString('vi-VN')}</span>}</button>; })}</div></div></div>;
}
